name: CICD PRACTICE

on:
  push:
    branches:
      - main

jobs:
  check-my-CICD:
    runs-on: ubuntu-latest

    steps:
      - name: check the code 
        uses: actions/checkout@v4

      - name: set up the build 
        uses: docker/setup-buildx-action@v3

      - name: login to docker 
        uses: docker/login-action@v3
        with:
         username: chethan2527
         password: 2527@docker

      - name: build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: chethan2527/etsnode:latest